# Generated by Django 5.1.1 on 2024-10-06 02:20

import django.db.models.deletion
import django_extensions.db.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created',
                 django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified',
                 django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('title', models.CharField(max_length=200, unique=True, verbose_name='Note Title')),
                ('md_file',
                 models.FileField(blank=True, null=True, upload_to='notes/md_files/', verbose_name='Markdown File')),
                ('text', models.TextField(blank=True, max_length=4000, null=True, verbose_name='Text Content')),
                ('is_grammar_correct', models.BooleanField(blank=True, null=True, verbose_name='Grammar Correct')),
                ('html_file',
                 models.FileField(blank=True, null=True, upload_to='notes/html_files/', verbose_name='HTML File')),
                ('thumbnail',
                 models.ImageField(blank=True, null=True, upload_to='notes/thumbnails/', verbose_name='Thumbnail')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes',
                                             to=settings.AUTH_USER_MODEL, verbose_name='Author')),
            ],
            options={
                'verbose_name': 'Note',
                'verbose_name_plural': 'Notes',
            },
        ),
    ]
